export const productosData = [
    {"codigo":"16PND69","nombre":"Beer - Sleemans Cream Ale","rotacion":"B","clasificacion":"B"},
    {"codigo":"00MYO07","nombre":"Syrup - Monin, Amaretta","rotacion":"B","clasificacion":"B"},
    {"codigo":"36UHI38","nombre":"Lettuce - Romaine, Heart","rotacion":"B","clasificacion":"A"},
    {"codigo":"99ISD15","nombre":"Horseradish Root","rotacion":"B","clasificacion":"B"},
    {"codigo":"25BQI29","nombre":"Sping Loaded Cup Dispenser","rotacion":"C","clasificacion":"B"},
    {"codigo":"53ZRO09","nombre":"Pineapple - Canned, Rings","rotacion":"B","clasificacion":"C"},
    {"codigo":"09JHH22","nombre":"Ice Cream Bar - Oreo Cone","rotacion":"C","clasificacion":"A"},
    {"codigo":"29VLD82","nombre":"Plastic Arrow Stir Stick","rotacion":"C","clasificacion":"C"},
    {"codigo":"99TII33","nombre":"Wine - White, Riesling, Semi - Dry","rotacion":"C","clasificacion":"B"},
    {"codigo":"82BZR97","nombre":"Wine - Kwv Chenin Blanc South","rotacion":"A","clasificacion":"C"},
    {"codigo":"71LCN04","nombre":"Wine - Stoneliegh Sauvignon","rotacion":"C","clasificacion":"A"},
    {"codigo":"00WZE56","nombre":"Wine - Cave Springs Dry Riesling","rotacion":"C","clasificacion":"B"},
    {"codigo":"41KER43","nombre":"Carbonated Water - White Grape","rotacion":"C","clasificacion":"C"},
    {"codigo":"18BSO70","nombre":"Lamb - Whole Head Off,nz","rotacion":"A","clasificacion":"B"},
    {"codigo":"77QDB64","nombre":"Beer - Corona","rotacion":"B","clasificacion":"A"},
    {"codigo":"84ZCW47","nombre":"Oil - Truffle, Black","rotacion":"A","clasificacion":"B"},
    {"codigo":"72GLM26","nombre":"Tomato - Green","rotacion":"A","clasificacion":"B"},
    {"codigo":"65HRC15","nombre":"Milk - 2%","rotacion":"C","clasificacion":"C"},
    {"codigo":"83XQM06","nombre":"Water - Mineral, Natural","rotacion":"B","clasificacion":"C"},
    {"codigo":"56OPX53","nombre":"Chilli Paste, Ginger Garlic","rotacion":"B","clasificacion":"B"},
    {"codigo":"50EHN61","nombre":"Bread - 10 Grain","rotacion":"B","clasificacion":"A"},
    {"codigo":"98YPG01","nombre":"Chicken Thigh - Bone Out","rotacion":"C","clasificacion":"A"},
    {"codigo":"85PXK01","nombre":"Alize Red Passion","rotacion":"C","clasificacion":"A"},
    {"codigo":"14UND36","nombre":"Lotus Leaves","rotacion":"B","clasificacion":"C"},
    {"codigo":"59YGC03","nombre":"Tortillas - Flour, 12","rotacion":"B","clasificacion":"B"},
    {"codigo":"86UOX08","nombre":"Monkfish - Fresh","rotacion":"B","clasificacion":"B"},
    {"codigo":"40HZW68","nombre":"Coffee - Colombian, Portioned","rotacion":"C","clasificacion":"B"},
    {"codigo":"40IHX35","nombre":"Oil - Truffle, Black","rotacion":"A","clasificacion":"C"},
    {"codigo":"15EUV65","nombre":"Urban Zen Drinks","rotacion":"A","clasificacion":"A"},
    {"codigo":"96FEY94","nombre":"Lemonade - Strawberry, 591 Ml","rotacion":"B","clasificacion":"C"},
    {"codigo":"01HVD66","nombre":"Buffalo - Striploin","rotacion":"B","clasificacion":"B"},
    {"codigo":"95IAA95","nombre":"Beef - Tongue, Cooked","rotacion":"A","clasificacion":"A"},
    {"codigo":"17RNT27","nombre":"Tomatoes - Cherry, Yellow","rotacion":"C","clasificacion":"A"},
    {"codigo":"91AVF56","nombre":"Spice - Montreal Steak Spice","rotacion":"B","clasificacion":"A"},
    {"codigo":"61SYZ85","nombre":"Yukon Jack","rotacion":"B","clasificacion":"C"},
    {"codigo":"61OPX18","nombre":"Pepper - Julienne, Frozen","rotacion":"C","clasificacion":"C"},
    {"codigo":"95KOK25","nombre":"Salt - Celery","rotacion":"A","clasificacion":"B"},
    {"codigo":"13EJZ77","nombre":"Tea - Honey Green Tea","rotacion":"C","clasificacion":"C"},
    {"codigo":"31ACU27","nombre":"Nut - Pine Nuts, Whole","rotacion":"C","clasificacion":"C"},
    {"codigo":"17EMY88","nombre":"Paper Cocktail Umberlla 80 - 180","rotacion":"B","clasificacion":"C"},
    {"codigo":"98BEM19","nombre":"Relish","rotacion":"A","clasificacion":"C"},
    {"codigo":"36SNW43","nombre":"Lemon Tarts","rotacion":"B","clasificacion":"B"},
    {"codigo":"12OGP15","nombre":"Carbonated Water - Blackcherry","rotacion":"C","clasificacion":"B"},
    {"codigo":"76GZR49","nombre":"Huck Towels White","rotacion":"B","clasificacion":"A"},
    {"codigo":"42FSV22","nombre":"Sparkling Wine - Rose, Freixenet","rotacion":"C","clasificacion":"A"},
    {"codigo":"77ZCK81","nombre":"Sugar - Individual Portions","rotacion":"C","clasificacion":"B"},
    {"codigo":"80JQA60","nombre":"Yams","rotacion":"B","clasificacion":"B"},
    {"codigo":"83DKJ11","nombre":"Chilli Paste, Ginger Garlic","rotacion":"C","clasificacion":"A"},
    {"codigo":"48NQZ27","nombre":"Container - Clear 16 Oz","rotacion":"A","clasificacion":"C"},
    {"codigo":"09SDU51","nombre":"Foil Wrap","rotacion":"B","clasificacion":"C"},
    {"codigo":"42AET02","nombre":"Plasticknivesblack","rotacion":"C","clasificacion":"B"},
    {"codigo":"76KNX37","nombre":"Wine - Chardonnay Mondavi","rotacion":"C","clasificacion":"B"},
    {"codigo":"18EYD78","nombre":"Bar Mix - Lemon","rotacion":"C","clasificacion":"A"},
    {"codigo":"70PSW91","nombre":"Wine - White, Chardonnay","rotacion":"C","clasificacion":"C"},
    {"codigo":"24LUC94","nombre":"Island Oasis - Pina Colada","rotacion":"B","clasificacion":"C"},
    {"codigo":"38FED35","nombre":"Bagel - Everything Presliced","rotacion":"B","clasificacion":"C"},
    {"codigo":"38PLH37","nombre":"Cheese - Bakers Cream Cheese","rotacion":"A","clasificacion":"B"},
    {"codigo":"07RVX91","nombre":"Beef - Eye Of Round","rotacion":"A","clasificacion":"C"},
    {"codigo":"42KZV75","nombre":"Garlic - Primerba, Paste","rotacion":"C","clasificacion":"B"},
    {"codigo":"13JFL33","nombre":"Salmon - Sockeye Raw","rotacion":"B","clasificacion":"C"},
    {"codigo":"74VAG63","nombre":"Peppercorns - Green","rotacion":"C","clasificacion":"B"},
    {"codigo":"10JTI60","nombre":"Energy - Boo - Koo","rotacion":"A","clasificacion":"A"},
    {"codigo":"63JEX81","nombre":"Goldschalger","rotacion":"C","clasificacion":"B"},
    {"codigo":"55PNE99","nombre":"Cheese - Mozzarella","rotacion":"C","clasificacion":"B"},
    {"codigo":"75SYC43","nombre":"Tomatoes - Cherry","rotacion":"C","clasificacion":"A"},
    {"codigo":"81CPN43","nombre":"Pastry - Chocolate Chip Muffin","rotacion":"B","clasificacion":"B"},
    {"codigo":"86AAO24","nombre":"Cream - 18%","rotacion":"C","clasificacion":"A"},
    {"codigo":"64XSE05","nombre":"Ecolab - Lime - A - Way 4/4 L","rotacion":"A","clasificacion":"B"},
    {"codigo":"93QVA96","nombre":"Soupfoamcont12oz 112con","rotacion":"B","clasificacion":"A"},
    {"codigo":"48VJT45","nombre":"Creme De Menthe Green","rotacion":"A","clasificacion":"A"},
    {"codigo":"89ZOF16","nombre":"Tea - Decaf 1 Cup","rotacion":"C","clasificacion":"A"},
    {"codigo":"30NIP23","nombre":"Glucose","rotacion":"C","clasificacion":"C"},
    {"codigo":"25RGC21","nombre":"Wine - Montecillo Rioja Crianza","rotacion":"B","clasificacion":"B"},
    {"codigo":"47EIS87","nombre":"Zucchini - Yellow","rotacion":"C","clasificacion":"A"},
    {"codigo":"26PTC50","nombre":"Island Oasis - Raspberry","rotacion":"C","clasificacion":"B"},
    {"codigo":"48RFW22","nombre":"Clementine","rotacion":"C","clasificacion":"A"},
    {"codigo":"58BYO07","nombre":"Sauce - Balsamic Viniagrette","rotacion":"A","clasificacion":"C"},
    {"codigo":"94NWN15","nombre":"Milk 2% 500 Ml","rotacion":"A","clasificacion":"A"},
    {"codigo":"79TLM22","nombre":"Juice - Apple 284ml","rotacion":"C","clasificacion":"C"},
    {"codigo":"82LPI83","nombre":"Beer - Paulaner Hefeweisse","rotacion":"C","clasificacion":"B"},
    {"codigo":"80DXG13","nombre":"Peppercorns - Green","rotacion":"A","clasificacion":"A"},
    {"codigo":"01FDY96","nombre":"Long Island Ice Tea","rotacion":"A","clasificacion":"B"},
    {"codigo":"20JXC68","nombre":"Rice - Long Grain","rotacion":"C","clasificacion":"B"},
    {"codigo":"38PJV98","nombre":"Chicken - Diced, Cooked","rotacion":"C","clasificacion":"A"},
    {"codigo":"19PPY70","nombre":"Wiberg Cure","rotacion":"A","clasificacion":"C"},
    {"codigo":"57TRA20","nombre":"Wine - Savigny - Les - Beaune","rotacion":"C","clasificacion":"C"},
    {"codigo":"04ZKP54","nombre":"Kellogs Special K Cereal","rotacion":"A","clasificacion":"C"},
    {"codigo":"32GFE60","nombre":"Beef - Top Sirloin","rotacion":"C","clasificacion":"A"},
    {"codigo":"22RUF95","nombre":"Nut - Pumpkin Seeds","rotacion":"A","clasificacion":"A"},
    {"codigo":"91LEJ46","nombre":"Soup Campbells - Tomato Bisque","rotacion":"C","clasificacion":"A"},
    {"codigo":"24VST97","nombre":"Beef - Bones, Cut - Up","rotacion":"C","clasificacion":"C"},
    {"codigo":"91IJZ28","nombre":"Dr. Pepper - 355ml","rotacion":"A","clasificacion":"C"},
    {"codigo":"93QFV84","nombre":"Juice - Tomato, 48 Oz","rotacion":"C","clasificacion":"C"},
    {"codigo":"51JXF49","nombre":"Crackers - Soda / Saltins","rotacion":"C","clasificacion":"C"},
    {"codigo":"72XRW02","nombre":"Fudge - Chocolate Fudge","rotacion":"C","clasificacion":"B"},
    {"codigo":"91CJO42","nombre":"Broom And Broom Rack White","rotacion":"B","clasificacion":"B"},
    {"codigo":"71ASY44","nombre":"Rice - Sushi","rotacion":"C","clasificacion":"B"},
    {"codigo":"77ULL72","nombre":"Pepper - Cayenne","rotacion":"C","clasificacion":"C"},
    {"codigo":"66IXV25","nombre":"Bread Cranberry Foccacia","rotacion":"A","clasificacion":"C"},
    {"codigo":"56ZRG73","nombre":"Chicken - Breast, 5 - 7 Oz","rotacion":"C","clasificacion":"C"},
    {"codigo":"28DRO71","nombre":"Beans - Green","rotacion":"A","clasificacion":"B"},
    {"codigo":"70NQB36","nombre":"Potato - Sweet","rotacion":"B","clasificacion":"C"},
    {"codigo":"39RUA68","nombre":"Wine - Alicanca Vinho Verde","rotacion":"C","clasificacion":"C"},
    {"codigo":"29AML80","nombre":"Pepper - Black, Whole","rotacion":"C","clasificacion":"C"},
    {"codigo":"91HAM39","nombre":"Chives - Fresh","rotacion":"C","clasificacion":"C"},
    {"codigo":"88KHW47","nombre":"Coffee - Flavoured","rotacion":"C","clasificacion":"C"},
    {"codigo":"36NUX13","nombre":"Veal - Provimi Inside","rotacion":"C","clasificacion":"A"},
    {"codigo":"36UVA14","nombre":"Marsala - Sperone, Fine, D.o.c.","rotacion":"A","clasificacion":"A"},
    {"codigo":"62QQV93","nombre":"Chicken Breast Halal","rotacion":"C","clasificacion":"B"},
    {"codigo":"40VER89","nombre":"Lemonade - Strawberry, 591 Ml","rotacion":"A","clasificacion":"C"},
    {"codigo":"82FNY94","nombre":"Cheese - Bocconcini","rotacion":"C","clasificacion":"A"},
    {"codigo":"70MFI55","nombre":"Cake - Sheet Strawberry","rotacion":"B","clasificacion":"A"},
    {"codigo":"56ZAD53","nombre":"Molasses - Fancy","rotacion":"C","clasificacion":"C"},
    {"codigo":"42CAF49","nombre":"Shiratamako - Rice Flour","rotacion":"C","clasificacion":"A"},
    {"codigo":"65QBL00","nombre":"Cheese - Blue","rotacion":"A","clasificacion":"C"},
    {"codigo":"17QCX72","nombre":"Bok Choy - Baby","rotacion":"C","clasificacion":"C"},
    {"codigo":"97KGQ96","nombre":"Cheese - Romano, Grated","rotacion":"A","clasificacion":"A"},
    {"codigo":"25QGP03","nombre":"Tea - Grapefruit Green Tea","rotacion":"B","clasificacion":"B"},
    {"codigo":"33IQP19","nombre":"Melon - Watermelon, Seedless","rotacion":"A","clasificacion":"B"},
    {"codigo":"14NNK54","nombre":"French Pastries","rotacion":"C","clasificacion":"A"},
    {"codigo":"93JQJ40","nombre":"Lettuce - Radicchio","rotacion":"A","clasificacion":"B"},
    {"codigo":"37QHR85","nombre":"Soup - Cream Of Broccoli, Dry","rotacion":"C","clasificacion":"A"},
    {"codigo":"89FHG79","nombre":"Appetizer - Veg Assortment","rotacion":"A","clasificacion":"C"},
    {"codigo":"26JUD53","nombre":"Salmon Steak - Cohoe 6 Oz","rotacion":"B","clasificacion":"B"},
    {"codigo":"90OLW99","nombre":"Sauce - Vodka Blush","rotacion":"B","clasificacion":"A"},
    {"codigo":"52UBE25","nombre":"Juice - Clam, 46 Oz","rotacion":"B","clasificacion":"B"},
    {"codigo":"01EPC50","nombre":"Lettuce - Lambs Mash","rotacion":"B","clasificacion":"A"},
    {"codigo":"47NXO84","nombre":"Parsley - Dried","rotacion":"C","clasificacion":"C"},
    {"codigo":"96PUW77","nombre":"Mint - Fresh","rotacion":"C","clasificacion":"C"},
    {"codigo":"76OZL94","nombre":"Piping - Bags Quizna","rotacion":"B","clasificacion":"A"},
    {"codigo":"01CHQ91","nombre":"Shark - Loin","rotacion":"B","clasificacion":"A"},
    {"codigo":"11KTV10","nombre":"Truffle Cups - Brown","rotacion":"C","clasificacion":"C"},
    {"codigo":"11YTV07","nombre":"Carbonated Water - Peach","rotacion":"B","clasificacion":"B"},
    {"codigo":"59ZZG09","nombre":"Coffee Cup 12oz 5342cd","rotacion":"C","clasificacion":"A"},
    {"codigo":"66BJW92","nombre":"Paper Towel Touchless","rotacion":"A","clasificacion":"B"},
    {"codigo":"97VAG69","nombre":"Bread - Malt","rotacion":"C","clasificacion":"A"},
    {"codigo":"72PRU05","nombre":"Flour Dark Rye","rotacion":"C","clasificacion":"C"},
    {"codigo":"81DJV93","nombre":"Shrimp - 16 - 20 Cooked, Peeled","rotacion":"C","clasificacion":"B"},
    {"codigo":"23ITQ96","nombre":"Beef - Ground, Extra Lean, Fresh","rotacion":"A","clasificacion":"A"},
    {"codigo":"08IRB93","nombre":"Red Currants","rotacion":"B","clasificacion":"A"},
    {"codigo":"76IBU04","nombre":"Gatorade - Orange","rotacion":"A","clasificacion":"C"},
    {"codigo":"20YIU77","nombre":"Compound - Pear","rotacion":"A","clasificacion":"C"},
    {"codigo":"06ZUC58","nombre":"Chickhen - Chicken Phyllo","rotacion":"A","clasificacion":"B"},
    {"codigo":"72RVI49","nombre":"Olive - Spread Tapenade","rotacion":"C","clasificacion":"B"},
    {"codigo":"22HGG67","nombre":"Beans - French","rotacion":"C","clasificacion":"A"},
    {"codigo":"82BWQ60","nombre":"Nut - Pistachio, Shelled","rotacion":"C","clasificacion":"C"},
    {"codigo":"06XTJ03","nombre":"Chilli Paste, Ginger Garlic","rotacion":"C","clasificacion":"A"},
    {"codigo":"55XFR44","nombre":"Pecan Raisin - Tarts","rotacion":"C","clasificacion":"B"},
    {"codigo":"00ZEY19","nombre":"Radish - Pickled","rotacion":"A","clasificacion":"A"},
    {"codigo":"08BGJ99","nombre":"Papadam","rotacion":"A","clasificacion":"B"},
    {"codigo":"28DCT92","nombre":"Vinegar - Cider","rotacion":"B","clasificacion":"C"},
    {"codigo":"80CSI56","nombre":"Soup - French Can Pea","rotacion":"C","clasificacion":"B"},
    {"codigo":"10YAT07","nombre":"Yogurt - Peach, 175 Gr","rotacion":"B","clasificacion":"C"},
    {"codigo":"89XGT44","nombre":"Basil - Pesto Sauce","rotacion":"B","clasificacion":"C"},
    {"codigo":"81VNJ48","nombre":"Dc Hikiage Hira Huba","rotacion":"A","clasificacion":"B"},
    {"codigo":"33OJU96","nombre":"Salt - Rock, Course","rotacion":"C","clasificacion":"A"},
    {"codigo":"13CBC53","nombre":"Artichoke - Fresh","rotacion":"C","clasificacion":"A"},
    {"codigo":"94NWM47","nombre":"Corn Kernels - Frozen","rotacion":"C","clasificacion":"C"},
    {"codigo":"85PQM91","nombre":"Beef - Ground Medium","rotacion":"C","clasificacion":"B"},
    {"codigo":"75TJZ21","nombre":"Bread - Focaccia Quarter","rotacion":"B","clasificacion":"A"},
    {"codigo":"47NNQ75","nombre":"Zucchini - Mini, Green","rotacion":"C","clasificacion":"B"},
    {"codigo":"22DVD67","nombre":"Melon - Watermelon, Seedless","rotacion":"A","clasificacion":"C"},
    {"codigo":"17EGM99","nombre":"Paper Cocktail Umberlla 80 - 180","rotacion":"C","clasificacion":"C"},
    {"codigo":"68HGJ43","nombre":"Oil - Olive","rotacion":"C","clasificacion":"C"},
    {"codigo":"56WLW19","nombre":"Snapple Raspberry Tea","rotacion":"A","clasificacion":"B"},
    {"codigo":"52DQW07","nombre":"Soup - Knorr, Veg / Beef","rotacion":"C","clasificacion":"B"},
    {"codigo":"98LUX61","nombre":"Lamb Rack - Ontario","rotacion":"B","clasificacion":"B"},
    {"codigo":"99YIB20","nombre":"Beef - Bones, Marrow","rotacion":"C","clasificacion":"A"},
    {"codigo":"82SBI49","nombre":"Soup - Campbells Mac N Cheese","rotacion":"B","clasificacion":"B"},
    {"codigo":"64KPY81","nombre":"Lotus Root","rotacion":"A","clasificacion":"B"},
    {"codigo":"74LTP99","nombre":"Lettuce - Sea / Sea Asparagus","rotacion":"C","clasificacion":"A"},
    {"codigo":"70CYO94","nombre":"Wine - Alsace Gewurztraminer","rotacion":"A","clasificacion":"B"},
    {"codigo":"58FPY74","nombre":"Crab - Claws, Snow 16 - 24","rotacion":"B","clasificacion":"B"},
    {"codigo":"57GVW61","nombre":"Bread - Burger","rotacion":"A","clasificacion":"B"},
    {"codigo":"81BTP01","nombre":"Orange - Blood","rotacion":"A","clasificacion":"A"},
    {"codigo":"88RQE93","nombre":"Pepsi - 600ml","rotacion":"C","clasificacion":"A"},
    {"codigo":"30IQP31","nombre":"Beef - Flank Steak","rotacion":"C","clasificacion":"C"},
    {"codigo":"14PGV67","nombre":"Salmon - Sockeye Raw","rotacion":"B","clasificacion":"C"},
    {"codigo":"57RNZ27","nombre":"Flour - Semolina","rotacion":"B","clasificacion":"C"},
    {"codigo":"33RIQ01","nombre":"Wine - Rhine Riesling Wolf Blass","rotacion":"C","clasificacion":"C"},
    {"codigo":"88RZR58","nombre":"Tomatoes Tear Drop","rotacion":"B","clasificacion":"C"},
    {"codigo":"05GMP74","nombre":"Basil - Fresh","rotacion":"B","clasificacion":"A"},
    {"codigo":"72PYU05","nombre":"Bread - Focaccia Quarter","rotacion":"C","clasificacion":"C"},
    {"codigo":"11ABW75","nombre":"Lid - 16 Oz And 32 Oz","rotacion":"C","clasificacion":"C"},
    {"codigo":"81MHX59","nombre":"Bar Bran Honey Nut","rotacion":"A","clasificacion":"A"},
    {"codigo":"64OUF94","nombre":"Glass - Juice Clear 5oz 55005","rotacion":"A","clasificacion":"B"},
    {"codigo":"88EDJ07","nombre":"Beef - Rouladin, Sliced","rotacion":"B","clasificacion":"C"},
    {"codigo":"90QPV06","nombre":"Temperature Recording Station","rotacion":"B","clasificacion":"A"},
    {"codigo":"19BOC32","nombre":"Lid - Translucent, 3.5 And 6 Oz","rotacion":"C","clasificacion":"C"},
    {"codigo":"28YML01","nombre":"Browning Caramel Glace","rotacion":"C","clasificacion":"C"},
    {"codigo":"19CAB20","nombre":"Oven Mitts 17 Inch","rotacion":"C","clasificacion":"B"},
    {"codigo":"40EPH76","nombre":"Cheese - Provolone","rotacion":"C","clasificacion":"B"},
    {"codigo":"58FAC76","nombre":"Cheese - Cheddar, Old White","rotacion":"B","clasificacion":"A"},
    {"codigo":"22GRF25","nombre":"Wanton Wrap","rotacion":"B","clasificacion":"B"},
    {"codigo":"24QHZ52","nombre":"Venison - Denver Leg Boneless","rotacion":"B","clasificacion":"C"},
    {"codigo":"07YQV21","nombre":"Dikon","rotacion":"C","clasificacion":"A"},
    {"codigo":"54BJA15","nombre":"Oneshot Automatic Soap System","rotacion":"B","clasificacion":"A"},
    {"codigo":"61YUH61","nombre":"Sesame Seed","rotacion":"B","clasificacion":"B"},
    {"codigo":"64BIS27","nombre":"Beer - Mcauslan Apricot","rotacion":"C","clasificacion":"A"},
    {"codigo":"70TUW89","nombre":"Beer - Molson Excel","rotacion":"B","clasificacion":"C"},
    {"codigo":"98MFP26","nombre":"Bols Melon Liqueur","rotacion":"A","clasificacion":"B"},
    {"codigo":"19RDM89","nombre":"Chives - Fresh","rotacion":"B","clasificacion":"A"},
    {"codigo":"94TGX85","nombre":"Dish Towel","rotacion":"B","clasificacion":"B"},
    {"codigo":"02SCG68","nombre":"Nestea - Iced Tea","rotacion":"C","clasificacion":"C"},
    {"codigo":"61PPQ91","nombre":"Salt - Kosher","rotacion":"A","clasificacion":"A"},
    {"codigo":"10FAE45","nombre":"Cookie Double Choco","rotacion":"B","clasificacion":"B"},
    {"codigo":"16AJU55","nombre":"Broom - Corn","rotacion":"A","clasificacion":"B"},
    {"codigo":"75TZO62","nombre":"Beer - Creemore","rotacion":"A","clasificacion":"B"},
    {"codigo":"24CLG52","nombre":"Cumin - Whole","rotacion":"A","clasificacion":"A"},
    {"codigo":"08PKU99","nombre":"Wine - Alsace Gewurztraminer","rotacion":"C","clasificacion":"B"},
    {"codigo":"96YIQ41","nombre":"Pork - Butt, Boneless","rotacion":"A","clasificacion":"C"},
    {"codigo":"29WAG50","nombre":"Apple - Granny Smith","rotacion":"A","clasificacion":"B"},
    {"codigo":"39LDA12","nombre":"Squeeze Bottle","rotacion":"A","clasificacion":"C"},
    {"codigo":"19QPV72","nombre":"Carrots - Purple, Organic","rotacion":"A","clasificacion":"A"},
    {"codigo":"86RCN90","nombre":"Table Cloth 72x144 White","rotacion":"B","clasificacion":"C"},
    {"codigo":"21JHR59","nombre":"Cocoa Butter","rotacion":"C","clasificacion":"C"},
    {"codigo":"13BJT57","nombre":"Wine - Sawmill Creek Autumn","rotacion":"B","clasificacion":"C"},
    {"codigo":"93KFV92","nombre":"Yogurt - Banana, 175 Gr","rotacion":"C","clasificacion":"A"},
    {"codigo":"89RCJ61","nombre":"Wine - Guy Sage Touraine","rotacion":"B","clasificacion":"B"},
    {"codigo":"36LQA56","nombre":"Potatoes - Fingerling 4 Oz","rotacion":"C","clasificacion":"B"},
    {"codigo":"94IOL16","nombre":"Petite Baguette","rotacion":"B","clasificacion":"C"},
    {"codigo":"18OOK69","nombre":"Pasta - Fusili Tri - Coloured","rotacion":"A","clasificacion":"A"},
    {"codigo":"42RRB70","nombre":"Table Cloth 91x91 Colour","rotacion":"A","clasificacion":"B"},
    {"codigo":"10EDG45","nombre":"Wine - Saint Emilion Calvet","rotacion":"C","clasificacion":"C"},
    {"codigo":"54QXW14","nombre":"Beef - Ground Medium","rotacion":"B","clasificacion":"B"},
    {"codigo":"65QPH12","nombre":"Lettuce - Green Leaf","rotacion":"A","clasificacion":"C"},
    {"codigo":"71ADI55","nombre":"Tomatoes - Plum, Canned","rotacion":"A","clasificacion":"B"},
    {"codigo":"11CHZ14","nombre":"Beef - Tender Tips","rotacion":"B","clasificacion":"C"},
    {"codigo":"66JSH43","nombre":"Champagne - Brights, Dry","rotacion":"B","clasificacion":"A"},
    {"codigo":"59BXW50","nombre":"Arrowroot","rotacion":"A","clasificacion":"B"},
    {"codigo":"21ZZQ06","nombre":"Almonds Ground Blanched","rotacion":"C","clasificacion":"B"},
    {"codigo":"12BXC20","nombre":"Sage Derby","rotacion":"C","clasificacion":"C"},
    {"codigo":"21TAM36","nombre":"Nut - Hazelnut, Whole","rotacion":"B","clasificacion":"B"},
    {"codigo":"15DYV73","nombre":"Loquat","rotacion":"C","clasificacion":"B"},
    {"codigo":"22UQM18","nombre":"Pheasants - Whole","rotacion":"A","clasificacion":"A"},
    {"codigo":"54WJS18","nombre":"Potatoes - Parissienne","rotacion":"C","clasificacion":"B"},
    {"codigo":"34URJ54","nombre":"Lotus Rootlets - Canned","rotacion":"C","clasificacion":"A"},
    {"codigo":"16ZXT85","nombre":"Ranchero - Primerba, Paste","rotacion":"C","clasificacion":"A"},
    {"codigo":"51PMW54","nombre":"Garbage Bag - Clear","rotacion":"C","clasificacion":"B"},
    {"codigo":"57HNM81","nombre":"Sugar - Brown, Individual","rotacion":"A","clasificacion":"C"},
    {"codigo":"78JFY11","nombre":"Soup - Campbells Beef Strogonoff","rotacion":"A","clasificacion":"A"},
    {"codigo":"59SRR74","nombre":"Veal - Liver","rotacion":"B","clasificacion":"B"},
    {"codigo":"02MQX06","nombre":"Cup - 8oz Coffee Perforated","rotacion":"B","clasificacion":"C"},
    {"codigo":"29GWR68","nombre":"Food Colouring - Blue","rotacion":"C","clasificacion":"A"},
    {"codigo":"13OZD54","nombre":"Asparagus - Mexican","rotacion":"B","clasificacion":"B"},
    {"codigo":"26JJW44","nombre":"Pepper - Jalapeno","rotacion":"C","clasificacion":"A"},
    {"codigo":"01UVS65","nombre":"Cookie - Oatmeal","rotacion":"B","clasificacion":"C"},
    {"codigo":"52IDI40","nombre":"Sausage - Andouille","rotacion":"A","clasificacion":"B"},
    {"codigo":"90MDG63","nombre":"Wine - Tribal Sauvignon","rotacion":"C","clasificacion":"A"},
    {"codigo":"73ORG47","nombre":"Bread - Burger","rotacion":"C","clasificacion":"A"}
]